//Node server's related actions.
export const CONNECTION_TO_NODE_SERVER_STARTED = 'CONNECTION_TO_NODE_SERVER_STARTED';
export const CONNECTION_TO_NODE_SERVER_CHANGED_STATUS = 'CONNECTION_TO_NODE_SERVER_CHANGED_STATUS';

//User actions
export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_RECEIVED_DATA = 'LOGIN_USER_RECEIVED_DATA';
