//Node server's related actions.
export const CONNECTION_TO_NODE_SERVER_STARTED = 'CONNECTION_TO_NODE_SERVER_STARTED';
export const CONNECTION_TO_NODE_SERVER_CHANGED_STATUS = 'CONNECTION_TO_NODE_SERVER_CHANGED_STATUS';
