// Main actions.
export const REQUEST_INTERVENTIONS_STARTED = 'REQUEST_INTERVENTIONS_STARTED';
export const REQUEST_INTERVENTIONS_RECEIVED_DATA = 'REQUEST_INTERVENTIONS_RECEIVED_DATA';

export const REQUEST_CUSTOMERS_STARTED = 'REQUEST_CUSTOMERS_STARTED';
export const REQUEST_CUSTOMERS_RECEIVED_DATA = 'REQUEST_CUSTOMERS_RECEIVED_DATA';

export const REQUEST_EMPLOYEES_STARTED = 'REQUEST_EMPLOYEES_STARTED';
export const REQUEST_EMPLOYEES_RECEIVED_DATA = 'REQUEST_EMPLOYEES_RECEIVED_DATA';

export const RECEIVED_NEW_INTERVENTION = 'RECEIVED_NEW_INTERVENTION';
export const RECEIVED_TECHNICIAN_ASSIGNATION = 'RECEIVED_TECHNICIAN_ASSIGNATION';

export const SET_USER_SIDE_PANEL_OPEN_STATE = 'SET_USER_SIDE_PANEL_OPEN_STATE';

// Utils actions.
export const WINDOW_WIDTH_CHANGED = 'WINDOW_WIDTH_CHANGED';
export const QUEUE_ACTION = 'QUEUE_ACTION';
export const CLEAR_QUEUED_ACTIONS = 'CLEAR_QUEUED_ACTIONS';

// Node server's related actions.
export const CONNECTION_TO_NODE_SERVER_STARTED = 'CONNECTION_TO_NODE_SERVER_STARTED';
export const CONNECTION_TO_NODE_SERVER_CHANGED_STATUS = 'CONNECTION_TO_NODE_SERVER_CHANGED_STATUS';

// User's related actions.
export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_RECEIVED_DATA = 'LOGIN_USER_RECEIVED_DATA';
